
(() => {
  const $=id=>document.getElementById(id);
  const sessionKey=localStorage.getItem("rsr-session-key")||(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`);
  localStorage.setItem("rsr-session-key",sessionKey);
  const track=eventType=>fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventType,sessionKey,path:location.pathname,language:document.documentElement.lang})}).catch(()=>{});
  track("page_view"); if(!$("submitOrder"))return;
  const panel=document.createElement("section");panel.className="panel v10-checkout";panel.innerHTML='<div class="section-title"><span>✓</span><div><h2>Smart Checkout Check</h2><p>Complete every requirement before submitting.</p></div></div><div id="v10Checklist" class="v10-checklist"></div><div class="v10-security-note">🛡️ Duplicate receipts and reference numbers are flagged for manual review. Never send your Roblox password, cookie, or verification code.</div>';
  $("submitOrder").closest("section").before(panel);
  const checks=()=>{const method=typeof selectedMethod!=="undefined"?selectedMethod:"ct",amount=Number($("amount")?.value||0),receipt=$("receipt")?.files?.[0],payment=document.querySelector('input[name="paymentMethod"]:checked')?.value,gp=["ct","nct"].includes(method);
    const items=[["Roblox account selected",Boolean(typeof selectedRoblox!=="undefined"&&selectedRoblox)],["Valid Robux amount entered",amount>0],["Game Pass verified at exact price",!gp||Boolean(typeof verifiedGamePassData!=="undefined"&&verifiedGamePassData)],["Payment method selected",Boolean(payment)],["Sender name entered",Boolean($("senderName")?.value.trim())],["Reference number entered",Boolean($("referenceNumber")?.value.trim())],["Clear receipt uploaded",Boolean(receipt)],["Information confirmation checked",Boolean($("confirm")?.checked)]];
    $("v10Checklist").innerHTML=items.map(([l,o])=>`<div class="${o?"done":"pending"}"><span>${o?"✓":"○"}</span><b>${l}</b></div>`).join("");return{ready:items.every(x=>x[1]),method,amount,payment,receipt};};
  ["input","change","click"].forEach(n=>document.addEventListener(n,()=>setTimeout(checks,0)));checks();
  const modal=document.createElement("div");modal.className="v10-confirm-modal hidden";modal.innerHTML='<div class="v10-confirm-card"><button class="v10-close" type="button">×</button><span class="eyebrow">FINAL CHECK</span><h2>Confirm Order Details</h2><div id="v10Summary" class="details-grid"></div><label class="confirm"><input id="v10FinalConfirm" type="checkbox"> I reviewed this summary and confirm it is correct.</label><button id="v10FinalSubmit" class="button primary full">Confirm & Submit Order</button></div>';document.body.appendChild(modal);
  modal.querySelector(".v10-close").onclick=()=>modal.classList.add("hidden");modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
  $("submitOrder").addEventListener("click",e=>{if(e.__v10Approved)return;e.preventDefault();e.stopImmediatePropagation();const s=checks();if(!s.ready){showToast?.("Complete every checkout requirement first.","error");panel.scrollIntoView({behavior:"smooth",block:"center"});return}
    track("order_submit_attempt");$("v10Summary").innerHTML=`<div><span>Method</span><b>${$("methodDisplay")?.textContent||s.method}</b></div><div><span>Roblox Username</span><b>${typeof selectedRoblox!=="undefined"&&selectedRoblox?"@"+selectedRoblox.username:""}</b></div><div><span>Desired Robux</span><b>${s.amount.toLocaleString()}</b></div><div><span>Required Game Pass</span><b>${$("gamepassRequiredPrice")?.textContent||"Not required"}</b></div><div><span>Payment Method</span><b>${s.payment}</b></div><div><span>Total Payment</span><b>${$("totalDisplay")?.textContent||""}</b></div><div><span>Receipt</span><b>${s.receipt?.name||""}</b></div><div><span>Reference</span><b>${$("referenceNumber")?.value||""}</b></div>`;$("v10FinalConfirm").checked=false;modal.classList.remove("hidden")},true);
  $("v10FinalSubmit").onclick=()=>{if(!$("v10FinalConfirm").checked)return showToast?.("Confirm the final summary first.","error");modal.classList.add("hidden");const ev=new MouseEvent("click",{bubbles:true,cancelable:true});Object.defineProperty(ev,"__v10Approved",{value:true});$("submitOrder").dispatchEvent(ev)};
  fetch("/api/settings").then(r=>r.json()).then(s=>{document.querySelectorAll("[data-method]").forEach(b=>{if(s.operations?.methods?.[b.dataset.method]===false){b.disabled=true;b.classList.add("method-disabled");b.insertAdjacentHTML("beforeend","<small>Temporarily unavailable</small>")}});if(s.operations?.ordersEnabled===false){$("submitOrder").disabled=true;$("submitMessage").className="message error";$("submitMessage").textContent="New orders are temporarily disabled. Existing orders can still be tracked."}}).catch(()=>{});
})();
