
(() => {
  const token=localStorage.getItem("rsr_token");if(!token)return;
  const api=async(url,opt={})=>{opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};if(opt.body)opt.headers["Content-Type"]="application/json";const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d};
  const main=document.querySelector("main.container");if(!main)return;
  const s=document.createElement("section");s.className="admin-grid v10-customer-center";s.innerHTML='<section class="panel"><div class="order-header"><div><h2>Notifications</h2><p class="muted">Order and support updates appear here.</p></div><button id="markNotifications">Mark read</button></div><div id="notificationList" class="orders-list"></div></section><section class="panel"><h2>Report an Order Problem</h2><label>Order Number<input id="disputeOrder" placeholder="RSR-..."></label><label>Problem<select id="disputeCategory"><option>Missing Delivery</option><option>Wrong Roblox Username</option><option>Wrong Game Pass</option><option>Duplicate Payment</option><option>Refund Request</option><option>Other</option></select></label><label>Details<textarea id="disputeDetails"></textarea></label><button id="submitDispute" class="button secondary full">Open Support Case</button><div id="disputeList" class="orders-list"></div></section>';main.appendChild(s);
  const load=async()=>{try{const n=await api("/api/customer/notifications");document.getElementById("notificationList").innerHTML=n.notifications.map(x=>`<div class="order-row ${x.read_at?"":"unread-row"}"><div><b>${x.title}</b><span>${x.message}</span></div><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join("")||'<p class="muted">No notifications yet.</p>';const d=await api("/api/customer/disputes");document.getElementById("disputeList").innerHTML=d.disputes.map(x=>`<div class="order-row"><div><b>${x.order_number} · ${x.category}</b><span>${x.admin_reply||x.details}</span></div><span class="status-pill">${x.status}</span></div>`).join("")||'<p class="muted">No support cases.</p>'}catch{}};
  document.getElementById("markNotifications").onclick=async()=>{await api("/api/customer/notifications/read",{method:"PATCH"});load()};
  document.getElementById("submitDispute").onclick=async()=>{try{const n=document.getElementById("disputeOrder").value.trim();await api(`/api/orders/${encodeURIComponent(n)}/disputes`,{method:"POST",body:JSON.stringify({category:document.getElementById("disputeCategory").value,details:document.getElementById("disputeDetails").value})});alert("Support case opened.");document.getElementById("disputeDetails").value="";load()}catch(e){alert(e.message)}};load();
})();
