"use strict";
const $=id=>document.getElementById(id);
const token=localStorage.getItem("rsrSession");
const user=JSON.parse(localStorage.getItem("rsrUser")||"null");
let cfg=null,selectedMethod="ct",selectedRoblox=null,discount=0,appliedPromo="";
const peso=n=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n)||0);
const num=n=>Number(n||0).toLocaleString();
async function api(url,options={}){options.headers={...(options.headers||{})};if(token)options.headers.Authorization=`Bearer ${token}`;const r=await fetch(url,options),t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{throw new Error(`Invalid server response (${r.status}).`)}if(!r.ok)throw new Error(d.error||`Request failed (${r.status}).`);return d}
if(token&&user){$("accountLink").textContent="My Dashboard";$("accountLink").href="dashboard.html"}
function paymentMethod(){return document.querySelector('input[name="paymentMethod"]:checked')?.value||"GCash"}
function calc(){
  const amount=Math.floor(Number($("amount").value)||0);let receive=amount,pass=0;
  if(selectedMethod==="ct")pass=Math.ceil(amount/.7);
  if(selectedMethod==="nct"){pass=amount;receive=Math.floor(amount*.7)}
  const subtotal=amount/1000*(cfg?.rates?.[selectedMethod]||0),total=Math.max(0,subtotal-discount);
  $("methodDisplay").textContent={ct:"Covered Tax",nct:"Not Covered Tax",instant:"Robux Instant",gifting:"In-Game Gifting"}[selectedMethod];
  $("receiveDisplay").textContent=`${num(receive)} Robux`;$("passDisplay").textContent=`${num(pass)} Robux`;
  $("passRow").classList.toggle("hidden",!["ct","nct"].includes(selectedMethod));
  $("subtotalDisplay").textContent=peso(subtotal);$("discountDisplay").textContent=`−${peso(discount)}`;
  $("totalDisplay").textContent=peso(total);$("exactAmount").textContent=peso(total);
  return{amount,receive,pass,subtotal,total}
}
async function start(){
  cfg=await api("/api/settings");
  $("supportStatus").textContent=cfg.supportOnline?"● Support Online":"● Support Away";$("supportStatus").classList.toggle("online",cfg.supportOnline);
  $("stockDisplay").textContent=`${num(cfg.instantStock)} Robux`;
  [["rateCt","ct"],["rateNct","nct"],["rateInstant","instant"],["rateGifting","gifting"]].forEach(([id,key])=>$(id).textContent=`₱${cfg.rates[key].toLocaleString("en-PH")} / 1,000`);
  calc();loadReviews();updatePayment();
}
document.querySelectorAll(".method-card").forEach(b=>b.onclick=()=>{selectedMethod=b.dataset.method;discount=0;appliedPromo="";$("promoCode").value="";$("promoMessage").textContent="";document.querySelectorAll(".method-card").forEach(x=>x.classList.toggle("active",x===b));$("giftingFields").classList.toggle("hidden",selectedMethod!=="gifting");calc()});
document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>{$("amount").value=b.dataset.amount;discount=0;appliedPromo="";calc()});$("amount").oninput=()=>{discount=0;appliedPromo="";calc()};
$("searchRoblox").onclick=async()=>{const b=$("searchRoblox");b.disabled=true;b.textContent="Searching…";try{selectedRoblox=await api(`/api/roblox/search?username=${encodeURIComponent($("usernameSearch").value.trim())}`);$("robloxAvatar").src=selectedRoblox.avatarUrl;$("robloxDisplayName").textContent=selectedRoblox.displayName;$("robloxUsername").textContent=`@${selectedRoblox.username}`;$("robloxUserId").textContent=`User ID: ${selectedRoblox.userId}`;$("robloxResult").classList.remove("hidden")}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="Search"}};
$("applyPromo").onclick=async()=>{if(!token)return location.href="auth.html";try{const c=calc(),d=await api("/api/promo/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:$("promoCode").value.trim(),subtotal:c.subtotal})});discount=d.discount||0;appliedPromo=d.code||"";$("promoMessage").className="message success";$("promoMessage").textContent=`Promo applied: −${peso(discount)}`;calc()}catch(e){discount=0;appliedPromo="";$("promoMessage").className="message error";$("promoMessage").textContent=e.message;calc()}};
function updatePayment(){document.querySelectorAll(".payment-card").forEach(c=>c.classList.toggle("active",c.querySelector("input").checked));const method=paymentMethod();const local=method==="GCash"||method==="GoTyme Bank";$("paymentQr").classList.toggle("hidden",!local);if(method==="GCash"){$("paymentQr").src="images/gcash-qr.png";$("paymentTitle").textContent="Pay through GCash";$("paymentInstructions").textContent="Scan the QR and pay the exact amount."}else if(method==="GoTyme Bank"){$("paymentQr").src="images/gotyme-qr.png";$("paymentTitle").textContent="Pay through GoTyme Bank";$("paymentInstructions").textContent="Scan the QR using an InstaPay-supported app."}else{$("paymentTitle").textContent=`Pay through ${method}`;const map={PayPal:cfg?.paymentDetails?.paypalEmail,Wise:cfg?.paymentDetails?.wiseDetails,Payoneer:cfg?.paymentDetails?.payoneerDetails};$("paymentInstructions").textContent=map[method]||`Contact support for the current ${method} payment details before paying.`}}
document.querySelectorAll('input[name="paymentMethod"]').forEach(i=>i.onchange=updatePayment);
$("submitOrder").onclick=async()=>{const msg=$("submitMessage");msg.className="message";msg.textContent="";if(!token){msg.className="message error";msg.innerHTML='Please <a href="auth.html">log in or register</a> before ordering.';return}const c=calc(),receipt=$("receipt").files[0];if(!selectedRoblox)return fail("Search and select the Roblox account.");if(c.amount<=0)return fail("Enter a valid amount.");if(selectedMethod==="instant"&&c.amount<10)return fail("Instant minimum is 10 Robux.");if(selectedMethod==="instant"&&c.amount>cfg.instantStock)return fail("Not enough Instant stock.");if(selectedMethod==="gifting"&&(!$("gameName").value.trim()||!$("itemName").value.trim()))return fail("Enter the game and item name.");if(!$("senderName").value.trim())return fail("Enter the sender name.");if($("referenceNumber").value.trim().length<5)return fail("Enter a valid payment reference.");if(!receipt)return fail("Upload the receipt.");if(!$("confirm").checked)return fail("Confirm the order information.");const form=new FormData();Object.entries({methodKey:selectedMethod,amount:c.amount,promoCode:appliedPromo,paymentMethod:paymentMethod(),senderName:$("senderName").value.trim(),referenceNumber:$("referenceNumber").value.trim(),robloxUserId:selectedRoblox.userId,username:selectedRoblox.username,robloxDisplayName:selectedRoblox.displayName,robloxAvatarUrl:selectedRoblox.avatarUrl,gameName:$("gameName").value.trim(),itemName:$("itemName").value.trim()}).forEach(([k,v])=>form.append(k,v));form.append("receipt",receipt);const b=$("submitOrder");b.disabled=true;b.textContent="Submitting…";try{const d=await api("/api/orders",{method:"POST",body:form});msg.className="message success";msg.innerHTML=`Order created: <b>${d.orderNumber}</b><br><a href="dashboard.html">Open your dashboard</a>`;cfg=await api("/api/settings");$("stockDisplay").textContent=`${num(cfg.instantStock)} Robux`}catch(e){fail(e.message)}finally{b.disabled=false;b.textContent="Submit Order"}function fail(t){msg.className="message error";msg.textContent=t}};
async function loadReviews(){try{const d=await api("/api/reviews");$("reviews").innerHTML=d.reviews.length?d.reviews.map(r=>`<article class="review-card"><div class="stars">${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</div><p>${escapeHtml(r.comment)}</p><b>${escapeHtml(r.full_name)}</b><small class="muted">${escapeHtml(r.method)}</small></article>`).join(""):'<p class="muted">No published reviews yet.</p>'}catch{$("reviews").innerHTML='<p class="muted">Reviews are temporarily unavailable.</p>'}}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
start().catch(e=>{$("submitMessage").className="message error";$("submitMessage").textContent=`Connection problem: ${e.message}`});
let deferredInstallPrompt=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;if($("installApp"))$("installApp").classList.remove("hidden")});if($("installApp"))$("installApp").onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$("installApp").classList.add("hidden")};function applyLive(x){if(!x?.settings)return;cfg=x.settings;$("supportStatus").textContent=cfg.supportOnline?"● Support Online":"● Support Away";$("supportStatus").classList.toggle("online",cfg.supportOnline);$("stockDisplay").textContent=`${num(cfg.instantStock)} Robux`;document.querySelectorAll(".payment-card").forEach(c=>{const v=c.querySelector("input")?.value,en=cfg.paymentEnabled?.[v]!==false;c.classList.toggle("hidden",!en)});if($("shopBanner")){$("shopBanner").textContent=cfg.banner?.text||"";$("shopBanner").classList.toggle("hidden",!cfg.banner?.enabled)}}setInterval(async()=>{try{applyLive(await api("/api/live"))}catch{}},10000);